"""add transfer transaction link

Revision ID: 2cb82bafb25a
Revises: 0012
Create Date: 2026-03-05 00:22:43.870631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb82bafb25a'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transfer_transaction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_transactions_transfer_transaction_id',
        'transactions',
        'transactions',
        ['transfer_transaction_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_transfer_transaction_id', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'transfer_transaction_id')
    # ### end Alembic commands ###
