export interface TzOption {
  value: string;
  label: string;
}

export const TIMEZONES: TzOption[] = [
  // Americas
  { value: "Pacific/Honolulu",               label: "Hawaii (HST)" },
  { value: "America/Anchorage",              label: "Alaska (AKST)" },
  { value: "America/Los_Angeles",            label: "Pacific Time – Los Angeles" },
  { value: "America/Vancouver",              label: "Pacific Time – Vancouver" },
  { value: "America/Phoenix",                label: "Mountain Time – Phoenix (no DST)" },
  { value: "America/Denver",                 label: "Mountain Time – Denver" },
  { value: "America/Chicago",                label: "Central Time – Chicago" },
  { value: "America/Mexico_City",            label: "Central Time – Mexico City" },
  { value: "America/New_York",               label: "Eastern Time – New York" },
  { value: "America/Toronto",                label: "Eastern Time – Toronto" },
  { value: "America/Halifax",                label: "Atlantic Time – Halifax" },
  { value: "America/St_Johns",               label: "Newfoundland – St. John's" },
  { value: "America/Sao_Paulo",              label: "Brazil – São Paulo" },
  { value: "America/Argentina/Buenos_Aires", label: "Argentina – Buenos Aires" },
  { value: "America/Santiago",               label: "Chile – Santiago" },
  { value: "America/Bogota",                 label: "Colombia – Bogotá" },
  { value: "America/Lima",                   label: "Peru – Lima" },
  { value: "America/Caracas",                label: "Venezuela – Caracas" },
  { value: "America/Montevideo",             label: "Uruguay – Montevideo" },
  // Europe
  { value: "Atlantic/Azores",                label: "Azores" },
  { value: "Europe/London",                  label: "UK – London (GMT/BST)" },
  { value: "Europe/Lisbon",                  label: "Portugal – Lisbon" },
  { value: "Europe/Dublin",                  label: "Ireland – Dublin" },
  { value: "Europe/Paris",                   label: "France – Paris (CET)" },
  { value: "Europe/Berlin",                  label: "Germany – Berlin" },
  { value: "Europe/Rome",                    label: "Italy – Rome" },
  { value: "Europe/Madrid",                  label: "Spain – Madrid" },
  { value: "Europe/Amsterdam",               label: "Netherlands – Amsterdam" },
  { value: "Europe/Brussels",                label: "Belgium – Brussels" },
  { value: "Europe/Zurich",                  label: "Switzerland – Zurich" },
  { value: "Europe/Stockholm",               label: "Sweden – Stockholm" },
  { value: "Europe/Oslo",                    label: "Norway – Oslo" },
  { value: "Europe/Copenhagen",              label: "Denmark – Copenhagen" },
  { value: "Europe/Helsinki",                label: "Finland – Helsinki" },
  { value: "Europe/Warsaw",                  label: "Poland – Warsaw" },
  { value: "Europe/Prague",                  label: "Czech Republic – Prague" },
  { value: "Europe/Budapest",                label: "Hungary – Budapest" },
  { value: "Europe/Bucharest",               label: "Romania – Bucharest" },
  { value: "Europe/Athens",                  label: "Greece – Athens" },
  { value: "Europe/Istanbul",                label: "Turkey – Istanbul" },
  { value: "Europe/Moscow",                  label: "Russia – Moscow" },
  { value: "Europe/Kiev",                    label: "Ukraine – Kyiv" },
  // Africa
  { value: "Africa/Cairo",                   label: "Egypt – Cairo" },
  { value: "Africa/Lagos",                   label: "Nigeria – Lagos (WAT)" },
  { value: "Africa/Nairobi",                 label: "Kenya – Nairobi (EAT)" },
  { value: "Africa/Johannesburg",            label: "South Africa – Johannesburg" },
  { value: "Africa/Casablanca",              label: "Morocco – Casablanca" },
  // Asia / Middle East
  { value: "Asia/Dubai",                     label: "UAE – Dubai (GST)" },
  { value: "Asia/Riyadh",                    label: "Saudi Arabia – Riyadh" },
  { value: "Asia/Tehran",                    label: "Iran – Tehran" },
  { value: "Asia/Karachi",                   label: "Pakistan – Karachi" },
  { value: "Asia/Kolkata",                   label: "India – Kolkata (IST)" },
  { value: "Asia/Colombo",                   label: "Sri Lanka – Colombo" },
  { value: "Asia/Kathmandu",                 label: "Nepal – Kathmandu" },
  { value: "Asia/Dhaka",                     label: "Bangladesh – Dhaka" },
  { value: "Asia/Yangon",                    label: "Myanmar – Yangon" },
  { value: "Asia/Bangkok",                   label: "Thailand – Bangkok (ICT)" },
  { value: "Asia/Jakarta",                   label: "Indonesia – Jakarta (WIB)" },
  { value: "Asia/Singapore",                 label: "Singapore (SGT)" },
  { value: "Asia/Kuala_Lumpur",              label: "Malaysia – Kuala Lumpur" },
  { value: "Asia/Hong_Kong",                 label: "Hong Kong (HKT)" },
  { value: "Asia/Shanghai",                  label: "China – Shanghai (CST)" },
  { value: "Asia/Taipei",                    label: "Taiwan – Taipei" },
  { value: "Asia/Manila",                    label: "Philippines – Manila" },
  { value: "Asia/Seoul",                     label: "South Korea – Seoul (KST)" },
  { value: "Asia/Tokyo",                     label: "Japan – Tokyo (JST)" },
  // Pacific / Oceania
  { value: "Australia/Perth",                label: "Australia – Perth (AWST)" },
  { value: "Australia/Darwin",               label: "Australia – Darwin (ACST)" },
  { value: "Australia/Adelaide",             label: "Australia – Adelaide" },
  { value: "Australia/Brisbane",             label: "Australia – Brisbane (AEST)" },
  { value: "Australia/Sydney",               label: "Australia – Sydney" },
  { value: "Australia/Melbourne",            label: "Australia – Melbourne" },
  { value: "Pacific/Auckland",               label: "New Zealand – Auckland (NZST)" },
  { value: "Pacific/Fiji",                   label: "Fiji" },
  { value: "Pacific/Guam",                   label: "Guam (ChST)" },
  { value: "UTC",                            label: "UTC (Coordinated Universal Time)" },
];
